### ISSUE TITLE
Push notifications for websites

### ISSUE THREAD

**Issue by ondrabus** [Kentico/community-content-backlog#15]
### Motivation

Push notifications enable fast delivery of important messages to website visitors.

The Notifications API lets a web page or app send notifications that are displayed outside the page at the system level; this lets web apps send information to a user even if the application is idle or in the background. This article looks at the basics of using this API in your own apps.

The Notifications API allows web pages to control the display of system notifications to the end user. These are outside the top-level browsing context viewport, so therefore can be displayed even when the user has switched tabs or moved to a different app. The API is designed to be compatible with existing notification systems, across different platforms.

### Proposed idea

Create an easy module / integration for existing websites that enables to use KC content as push notification on these websites.

**Comment by kentico-ericd** [comment]
Working sample on https://github.com/Kentico/kontent-sample-app-express-js, will update README with some notes and write an article

**Comment by Simply007** [comment]
ping @ondrabus

**Comment by kentico-ericd** [comment]
btw, article is here: https://app.kontent.ai/4e9bdd7a-2db8-4c33-a13a-0c368ec2f108/content-inventory/00000000-0000-0000-0000-000000000000/content/bead77c2-83b1-422a-889a-c0e1c72768d4

**Comment by petrsvihlik** [comment]
This is cool, Eric!

Two notes: 
- I'd update the readme of the express app to highlight that it contains notifications (a few lines about how it works, where to find it, how to configure it...)
- I'd add some visuals to the article (maybe even an animated gif)

**Comment by ondrabus** [comment]
Article proofread and scheduled for publishing on Kontent.ai blog next week.
