### ISSUE TITLE
Importing JSON project templates into KC using CM API

### ISSUE THREAD

**Issue by ondrabus** [Kentico/community-content-backlog#2]
### Motivation

Tool for importing content models and content items will enable the community to create project/website templates. That speeds up adoption of KC by less experienced users.

### Proposed points

* create a tool that will enable import of content models and content items into Kentico Cloud using CM API
* host that tool online using WebTask or Azure Functions
* write an article about the use cases for this tool
* explain how the tool was built

**Comment by ondrabus** [comment]
The tool is currently being developed internally. Once it is ready for use, I will let you know @ileshmistry.

**Comment by Simply007** [comment]
We already have it covered in:
* https://kenticocloud.com/blog/launching-a-website-from-headless-web-templates
