### ISSUE TITLE
Integration with Zapier, IFTTT

### ISSUE THREAD

**Issue by ondrabus** [Kentico/community-content-backlog#6]
### Motivation

Zapier is a large integration platform covering a lot of potential integration use-cases.

### Proposed solution

Create meaningful integration with third-party service (IFTTT) through Zapier (webhooks).

**Comment by kentico-ericd** [comment]
I'm confused, this would use _both_ Zapier and IFTTT? What would a simple example be?

**Comment by ondrabus** [comment]
@kentico-ericd Sending data to Zapier happens via webhooks. The rest of the process is Zapier's job, including the possible IFTTT integration. However, if you want to go straight to IFTTT, that would work too.

**Comment by kentico-ericd** [comment]
I wrote a quick Zap which creates a new Google Calendar event when you publish some event item in Kontent. Do you guys think that's good enough for an article?

Right now it just adds the event, do you think an Email step would be good too (e.g. email all attendees about the event)?

**Comment by Simply007** [comment]
@kentico-ericd - just a couple of resources that might simplify the work:

Just two internal links with some info that might be useful:
* https://kentico.atlassian.net/browse/CN-64
* https://kentico.atlassian.net/browse/KCR-179

An @kenticomartinh is/was working on the zappier integration - it might worth to discuss his progress:
* https://kentico.atlassian.net/browse/DEVREL-132

**Comment by ondrabus** [comment]
@kentico-ericd, a cool use-case would be to have a field "Note to attendees" on the Event content type and once an event is created, you can create a new Google Calendar event and send it to all attendees (including the note) using SendGrid or some other provider.
Here I would stop the implementation. What you can explain as a possible extension is:
When someone is added as an attendee, you could inspect the previous versions of the Event content item and send the event only to the added attendee.

**Comment by kentico-ericd** [comment]
The project is currently "done" (note the quotes 😄) and I'll post a link to try it out in the next meeting: https://github.com/kentico-ericd/kc-zapierapp. I'm also going to have a meeting with the US support guys where we all test it and they offer feedback (bugs, feature requests, etc)

**Comment by kenticomartinh** [comment]
Nice! Just note that unless you already got through the review process with Zapier, from what I know they request at most 5 pieces in the first version.

So you may need to pick only some from this set: "This integration contains 4 triggers, 4 actions, and 2 searches:"

**Comment by kentico-ericd** [comment]
😮 I haven't gone through the process (waiting for some testers), but that's okay I can just disable some of them and release them afterward

**Comment by petrsvihlik** [comment]
https://zapier.com/blog/updates/2365/new-integration-kentico-kontent
