### ISSUE TITLE
JAMstack

### ISSUE THREAD

**Issue by ondrabus** [Kentico/community-content-backlog#8]
### Motivation

JAMstack is a methodology on modern website building.

### Proposed solution

Build a (client) site using JAMstack (Javascript, Kentico Cloud) and summarize the process and its overall benefits in an article or video.

**Comment by petrsvihlik** [comment]
https://dev.to/onyxprime/is-jamstack-suitable-for-anything-more-than-a-microsite-fp1

https://www.youtube.com/watch?v=_NQla316mWc&list=PLIxQ61Q5K6QcFCwMLRTG5jVoJBgTbNN6r
